jesi/blog/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('blog.views',
    url(r'^$', 'index'),
    url(r'^page/(?P<page_id>[\d]+)/$', 'index'),
    url(r'^cat/(?P<cat_name>[^/]+)/$', 'category'),
    url(r'^tag/(?P<cat_name>[^/]+)/page/(?P<page_id>[\d]+)/$', 'category'),
    url(r'^tag/(?P<tag_name>[^/]+)/$', 'tag'),
    url(r'^tag/(?P<tag_name>[^/]+)/page/(?P<page_id>[\d]+)/$', 'tag'),
    url(r'^(?P<post_id>[\d]+)/$', 'detail'),
    url(r'^(?P<post_id>[\d]+)/comment/$', 'comment'),
)

jesi/jesi/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView
from feeds import LatestBlogs

admin.autodiscover()

feeds = {
    'latest': LatestBlogs,
}

urlpatterns = patterns('',
    url(r'^$', 'views.index', name='index'),
    url(r'^about/', include('about.urls')),
    url(r'^accounts/login/', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/', 'django.contrib.auth.views.logout_then_login'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^photos/', include('photos.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.Feed', {'feed_dict': feeds}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT }),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt')),
    url(r'^sitemap\.xml$', TemplateView.as_view(template_name='sitemap.xml')),
)

jesi/blog/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User, Group

class Category(models.Model):
    title = models.CharField(max_length=200)
    
    def __unicode__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(max_length=200)
    
    def __unicode__(self):
        return self.title

class Post(models.Model):
    category = models.ForeignKey(Category, blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    groups = models.ManyToManyField(Group, blank=True)
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)
    is_public = models.BooleanField(default=True)
    
    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return settings.SITE_URL + 'blog/' + str(self.id) + '/'

class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(User, blank=True, null=True)
    author_name = models.CharField(max_length=200, null=True)
    author_email = models.EmailField(null=True)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    is_public = models.BooleanField(default=True)
    
    def __unicode__(self):
        result = ''
        if self.author:
            result = self.author.username
        else:
            result = self.author_name
        return result + ': ' + self.content

jesi/blog/forms.py
from django.forms import ModelForm
from blog.models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('author_name','author_email','content')

jesi/blog/views.py
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.db.models import Q
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.conf import settings
from blog.models import Category, Tag, Post, Comment
from blog.forms import CommentForm
from recaptcha.client import captcha
from django.core.mail import send_mail
from django.contrib.auth.models import User
from links.models import Link
from verses.models import Verse
import math

def index(request, page_id=1):
    info = {}
    per_page = 5
    
    if request.user.is_authenticated():
        all_posts = Post.objects.filter(is_public=True).filter(Q(groups__in=request.user.groups.all()) | Q(groups__isnull=True)).order_by('-created_date')
    else:
        all_posts = Post.objects.filter(is_public=True).filter(groups__isnull=True).order_by('-created_date')
    
    paginator = Paginator(all_posts, per_page)
    
    try:
      page = int(page_id)
    except ValueError:
      page = 1
    
    try:
      info['posts'] = paginator.page(page)
    except (EmptyPage, InvalidPage):
      info['posts'] = paginator.page(paginator.num_pages)
    
    for post in info['posts'].object_list:
        post.comment_list = Comment.objects.filter(post=post)
    
    info['links'] = Link.objects.filter(is_public=True)
    
    verses = Verse.objects.filter(is_public=True).order_by('?')
    info['verse'] = verses[0]
    
    info['active'] = 'blog'
    
    return render_to_response('blog/index.html', { 'info': info }, context_instance=RequestContext(request))

def category(request, cat_name, page_id=1):
    info = {}
    
    info['page_id'] = int(page_id)
    start_index = 5 * (info['page_id'] - 1)
    end_index = start_index + 5
    
    cat = Category.objects.get(title=cat_name)
    
    if request.user.is_authenticated():
        all_posts = Post.objects.filter(is_public=True).filter(Q(groups__in=request.user.groups.all()) | Q(groups__isnull=True)).filter(category=cat).order_by('created_date')
    else:
        all_posts = Post.objects.filter(is_public=True).filter(groups__isnull=True).filter(category=cat).order_by('-created_date')
    
    info['posts'] = all_posts[start_index:end_index]
    info['num_pages'] = math.ceil(all_posts.count() / 5.0)
    
    info['blog_nav'] = True
    if info['page_id'] == 1:
        if info['page_id'] == info['num_pages']:
            info['blog_nav'] = False
    
    # If invalid page number, redirect to home page
    if info['posts'].count() == 0:
        return redirect('/')
    
    for post in info['posts']:
        post.comment_list = Comment.objects.filter(post=post)
    
    verses = Verse.objects.filter(is_public=True).order_by('?')
    info['verse'] = verses[0]
    
    info['active'] = 'blog'
    
    return render_to_response('blog/index.html', { 'info': info }, context_instance=RequestContext(request))

def tag(request, tag_name, page_id=1):
    info = {}
    
    info['page_id'] = int(page_id)
    start_index = 5 * (info['page_id'] - 1)
    end_index = start_index + 5
    
    tag = Tag.objects.get(title=tag_name)
    
    if request.user.is_authenticated():
        all_posts = Post.objects.filter(is_public=True).filter(Q(groups__in=request.user.groups.all()) | Q(groups__isnull=True)).filter(tags=tag.id).order_by('created_date')
    else:
        all_posts = Post.objects.filter(is_public=True).filter(groups__isnull=True).filter(tags=tag.id).order_by('-created_date')
    
    info['posts'] = all_posts[start_index:end_index]
    info['num_pages'] = math.ceil(all_posts.count() / 5.0)
    
    info['blog_nav'] = True
    if info['page_id'] == 1:
        if info['page_id'] == info['num_pages']:
            info['blog_nav'] = False
    
    # If invalid page number, redirect to home page
    if info['posts'].count() == 0:
        return redirect('/')
    
    for post in info['posts']:
        post.comment_list = Comment.objects.filter(post=post)
    
    verses = Verse.objects.filter(is_public=True).order_by('?')
    info['verse'] = verses[0]
    
    info['active'] = 'blog'
    
    return render_to_response('blog/index.html', { 'info': info }, context_instance=RequestContext(request))

def detail(request, post_id):
    info = {}
    
    info['post'] = Post.objects.get(pk=post_id)
    info['comment_list'] = Comment.objects.filter(post=info['post'])
    info['form'] = CommentForm()

    info['links'] = Link.objects.filter(is_public=True)
    
    for c in info['comment_list']:
        if c.author_id:
            u = User.objects.get(pk=c.author_id)
            c.author_name = u.username
            c.author_email = u.email
    
    verses = Verse.objects.filter(is_public=True).order_by('?')
    info['verse'] = verses[0]
    
    info['active'] = 'blog'
    
    return render_to_response('blog/detail.html', { 'info': info }, context_instance=RequestContext(request))

def comment(request, post_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            if not request.user.is_authenticated():
                r = captcha.submit(request.POST['recaptcha_challenge_field'], request.POST['recaptcha_response_field'], settings.RECAPTCHA_PRIVATE_KEY, request.META['REMOTE_ADDR'])
                if not r.is_valid:
                    return redirect('/blog/'+post_id+'/') # Invalid form entry
            f = form.save(commit=False);
          
            f.post_id = post_id
            if request.user.is_authenticated():
                f.author_id = request.user.id
                f.author_name = ''
                f.author_email = ''
            f.save()
        
            email_msg  = 'You have a new comment at http://www.jessicasteiber.com/blog/'+post_id+'/#comments'
            email_from = 'no-reply@jessicasteiber.com'
            email_to   = ['jesi@jessicasteiber.com', 'alan@alanbeam.net']
        
            # Send email notification
            send_mail('New Blog Comment - JessicaSteiber.com', email_msg, email_from, email_to)
        
            return redirect('/blog/'+post_id+'/#comments') # Go back to blog with new comment
        else:
            return redirect('/blog/'+post_id+'/') # Invalid form entry
    else:
        return redirect('/blog/'+post_id+'/') # Go back to blog

jesi/templates/blog/detail.html
{% extends "base.html" %}

{% load gravatar %}

{% block keywords %}{{ info.post.title }},{% endblock keywords %}

{% block content %}          
          <h1><a href="/blog/{{ info.post.id }}/">{{ info.post.title }}</a></h1>
          
          <p class="blog_meta" style="float:left;">
            <span class="timestamp">{{ info.post.created_date|date:"m.d.Y G:i" }}</span>
            <span class="comments">{{ info.post.comment_list|length }} Comment{{ info.post.comment_list|length|pluralize }}</span>
          </p>
          
          <p class="blog_meta">
            <span class='st_facebook' displayText=''></span>
            <span class='st_twitter' displayText=''></span>
            <span class='st_googleplus' displayText=''></span>
            <span class='st_email' displayText=''></span>
          </p>
          
          <p class="text">{% autoescape off %}{{ info.post.content|linebreaksbr|safe }}{% endautoescape %}</p>
          
          <p class="divider"></p>
          
          {% for comment in info.comment_list %}
          <div class="comment">
            <p class="commentAvatar">
              <a name="comment{{ comment.id }}"></a>
              
              <img alt="Gravatar" src="http://www.gravatar.com/avatar/{{ comment.author_email|gravatar }}?d=identicon" />
            </p>
            
            <p class="commentText">
              <span class="commentAuthor">{{ comment.author_name }}</span>
              <span class="commentContent">{{ comment.content|linebreaks }}</span>
            </p>
          </div>
          {% empty %}
          <p>No comments yet!</p>
          {% endfor %}
          
          <p class="divider"></p>
          
          <div id="comment_div">
            <form id="comment_form" action="/blog/{{ info.post.id }}/comment/" method="post">{% csrf_token %}
            <p>
              <label for="id_author_name">Name:</label> {{ info.form.author_name }}
              <label for="id_author_email">Email:</label> {{ info.form.author_email }}
              
              <label for="id_content">Comment:</label> 
              {{ info.form.content }}
              
              <label>&nbsp;</label>
            </p>
            
            <div id="id_recaptcha" style="float: left; margin-bottom: 10px;"></div>
            
            <p>
              <label>&nbsp;</label>
              <input type="button" class="primary" value="Post" onclick="$('#comment_form').submit();" />
              <input type="hidden" name="post_id" value="{{ info.post.id }}" />
            </p>
            </form>
				  </div> <!-- </div id="comment_div"> -->
          
          <br class="clear" />
{% endblock %}

{% block jquery %}
    Recaptcha.create("6LcE-9gSAAAAACLay7g2WGkch9OitSXRBfwM7aEv", "id_recaptcha", { theme: "white" } );
    
    var switchTo5x=true;
    stLight.options({ publisher: "2d014aad-eb5d-4531-a4b8-35edf0e037e9", onhover: false });
{% endblock jquery %}

jesi/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
          {% for post in info.posts.object_list %}
          <h1><a href="/blog/{{ post.id }}/">{{ post.title }}</a></h1>
          
          <p class="text">
            {% autoescape off %}{{ post.content|linebreaksbr|safe }}{% endautoescape %}
          </p>
          
          <p class="left">
            <input type="button" class="secondary" value="Read More" onclick="window.location.href='/blog/{{ post.id }}';" />
          </p>
          
          <p class="blog_meta">
            <span class="timestamp">{{ post.created_date|date:"m.d.Y G:i" }}</span>
            <span class="comments">{{ post.comment_list|length }} Comment{{ post.comment_list|length|pluralize }}</span>
          </p>
          {% endfor %}
          
          <p id="pages">
            {% if info.posts.has_previous %}
            <a id="prev" href="/blog/page/{{ info.posts.previous_page_number }}/">Previous Page</a>
            {% endif %}
            
            {% if info.posts.has_next %}
            <a id="next" href="/blog/page/{{ info.posts.next_page_number }}/">Next Page</a>
            {% endif %}
          </p>
{% endblock content %}