jesi/blog/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('blog.views',
    url(r'^$', 'index'),
    url(r'^page/(?P<page_id>[\d]+)/$', 'index'),
    url(r'^cat/(?P<cat_name>[^/]+)/$', 'category'),
    url(r'^tag/(?P<cat_name>[^/]+)/page/(?P<page_id>[\d]+)/$', 'category'),
    url(r'^tag/(?P<tag_name>[^/]+)/$', 'tag'),
    url(r'^tag/(?P<tag_name>[^/]+)/page/(?P<page_id>[\d]+)/$', 'tag'),
    url(r'^(?P<post_id>[\d]+)/$', 'detail'),
    url(r'^(?P<post_id>[\d]+)/comment/$', 'comment'),
)

jesi/contact/urls.py
from django.conf.urls import patterns

urlpatterns = patterns('contact.views',
    (r'^$', 'index'),
)

jesi/jesi/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView
from feeds import LatestBlogs

admin.autodiscover()

feeds = {
    'latest': LatestBlogs,
}

urlpatterns = patterns('',
    url(r'^$', 'views.index', name='index'),
    url(r'^about/', include('about.urls')),
    url(r'^accounts/login/', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/', 'django.contrib.auth.views.logout_then_login'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^photos/', include('photos.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.Feed', {'feed_dict': feeds}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT }),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt')),
    url(r'^sitemap\.xml$', TemplateView.as_view(template_name='sitemap.xml')),
)

jesi/contact/models.py
from django import forms

class ContactForm(forms.Form):
    name    = forms.CharField(max_length=100)
    email   = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

jesi/contact/views.py
from django.conf import settings
from django.core.mail import EmailMessage
from django.shortcuts import render_to_response, redirect
from django.shortcuts import render
from django.template import RequestContext
from contact.models import ContactForm
from recaptcha.client import captcha
from verses.models import Verse
from links.models import Link


def index(request):
    info = {}
    
    info['links'] = Link.objects.filter(is_public=True)
    
    if request.method == 'POST': # If the form has been submitted...
        form = ContactForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            r = captcha.submit(request.POST['recaptcha_challenge_field'], request.POST['recaptcha_response_field'], settings.RECAPTCHA_PRIVATE_KEY, request.META['REMOTE_ADDR'])
            if not r.is_valid:
                return redirect('/contact/') # Invalid form entry
            
            # Process the data in form.cleaned_data
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            recipients = ['jesi@jessicasteiber.com', 'alan@alanbeam.net']
            
            email = EmailMessage('Contact Message From ' + name + ' - JessicaSteiber.com', message, email, recipients)
            email.send()
            
            info['msg'] = '<p class="success">Message successfully sent.</p>'
            info['form'] = ContactForm()
    else:
        info['form'] = ContactForm() # An unbound form
        info['msg'] = ''
    
    verses = Verse.objects.filter(is_public=True).order_by('?')
    info['verse'] = verses[0]
    
    info['active'] = 'contact'
    
    return render_to_response('contact/index.html', { 'info': info }, context_instance=RequestContext(request))

jesi/templates/contact/index.html
{% extends "base.html" %}

{% block content %}
          <h1>Contact</h1>

          {% if info.msg != '' %}
          {% autoescape off %}{{ info.msg }}{% endautoescape %}
          {% else %}
          <form id="contact_form" action="/contact/" method="post">{% csrf_token %}
          <p>
            <label for="id_name">Name:</label> {{ info.form.name }}
            <label for="id_email">Email:</label> {{ info.form.email }}
            <label for="id_message">Message:</label> {{ info.form.message }}
            <label>&nbsp;</label>
          </p>
          
          <div id="id_recaptcha" style="float: left; margin-bottom: 10px;"></div>

          <p style="clear:both;">
            <label>&nbsp;</label>
            <input type="button" class="primary" value="Send" onclick="#('contact_form').submit();" />
          </p>
          </form>
          {% endif %}
{% endblock content %}

{% block jquery %}    
    Recaptcha.create("6Lde1LsSAAAAACR6c-nwLfOOFbkddHKLftEJlyIH", "id_recaptcha", { theme: "white" } );
{% endblock jquery %}